### ISSUE TITLE
Creating Domain Users

### ISSUE THREAD

**Issue by calex80** [dievus/ADGenerator#2]
When I run this command below I am receiving error "New-ADUser : The server is unwilling to process the request"
     ADGenerator-main> Invoke-ADGenerator -DomainName <domain name>
--------------------------------------
New-ADUser : The server is unwilling to process the request
At C:\Users\Administrator\Desktop\ADGenerator-main\ADGenerator.ps1:86 char:1
+ New-ADUser -Name "$firstname $lastname" -GivenName $firstname -Surnam ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (CN=Aaron Adams,...yorsec,DC=local:String) [New-ADUser], ADException
    + FullyQualifiedErrorId : ActiveDirectoryServer:0,Microsoft.ActiveDirectory.Management.Commands.NewADUser

        [+] a.adams added
        [+] Adding a.adams to Senior Management Group
Add-ADGroupMember : Cannot find an object with identity: 'a.adams' under: 'DC=homesec,DC=local'.
At C:\Users\Administrator\Desktop\ADGenerator-main\ADGenerator.ps1:89 char:1
+ Add-ADGroupMember -Identity $Global:Senior -Members $samAccountName
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (a.adams:ADPrincipal) [Add-ADGroupMember], ADIdentityNotFoundException
    + FullyQualifiedErrorId : SetADGroupMember.ValidateMembersParameter,Microsoft.ActiveDirectory.Management.Commands.
   AddADGroupMember

**Comment by dievus** [comment]
User error. The script is meant to be used with the courses listed in the readme. If the domain is not named mayorsec.local it will not work. 

Closing.

**Comment by calex80** [comment]
Thank you dievus, make sense!
