### ISSUE TITLE
forestdeploy does nothing

### ISSUE THREAD

**Issue by Th3Gr1ff** [dievus/ADGenerator#5]
I run the forestdeploy script using -DomainName mayorsec.local and it doesnt so anything, just new line. following along from the TCM video course.

**Comment by dievus** [comment]
Your issue is vague and doesn't help try to diagnose the issue. Additionally, this Github page isn't the appropriate place to receive course support. Please use the appropriate Github link provided in the course.

Closing.

**Comment by Th3Gr1ff** [comment]
This isnt for course support, the PS script does....nothing. i mention the course because i followed its instructions exactly, from building the OS in a VM to running those scripts. running the invoke-forestdeploy script just gives me a new line. it does nothing.
